### PR TITLE
Doc enhancer

### PR DESCRIPTION
**Pull request by farhan7reza7**
# Pull Request

## Description

[Provide a brief description of the changes made in this pull request]

## Related Issue

[If applicable, reference the related issue]

## Changes Made

[Briefly List the main changes made in this pull request]

## Screenshots (if applicable)

[Include any relevant screenshots]

## Checklist

- [ ] I have tested these changes thoroughly
- [ ] My code follows the project's coding standards
- [ ] I have documented(followed above Description and Changes Made) any necessary changes
- [ ] I have updated the README if needed (Optional)

### CODE REVIEW

**Comment by farhan7reza7** [comment]
merge 18 commits into [diff-ymd-package:main](https://github.com/diff-ymd-package/diff-ymd-package/tree/main) from [farhan7reza7:doc-enhancer](https://github.com/farhan7reza7/diff-ymd-package/tree/doc-enhancer)

**Review by spirito7phil — APPROVED** [review]
updated to main branch of diff-ymd-package on @farhan7reza7

**Comment by farhan7reza7** [comment]
everything is okay...

**Review by farhan7reza7 — COMMENTED** [review]
everything will be uptodated to main branch, mergable as expected

**Pull request merged**
